name: Build Helium

on: push

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive
      
    - name: Switch to Xcode 15
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: Install theos
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

    - name: Setup Environment
      run: echo "THEOS=~/theos" >> $GITHUB_ENV

    - name: Set env
      run: |
        sT=$(TZ=UTC-8 date +'%S')
        echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
        echo "logT=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" >> $GITHUB_ENV

    - name: Print env
      run: |
        echo ${{ env.msT }}
        echo ${{ env.logT }}
        echo ${{ github.ref }}

    - name: Make IPA
      run: ./ipabuild.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: Helium.tipa
          path: ${{ github.workspace }}/build/Helium.tipa

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ env.logT }}
        generate_release_notes: true
        files: |
          ${{ github.workspace }}/build/Helium.tipa